MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: vgg16.dilated_conv5_body
  WITH_FRCNN: True
NUM_GPUS: 2
VGG:
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/vgg16_caffe.pth'
SOLVER:
  WEIGHT_DECAY: 0.0005
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001
  GAMMA: 0.1
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  MAX_ITER: 70000
  STEPS: [0, 50000]
FAST_RCNN:
  ROI_BOX_HEAD: vgg16.roi_2mlp_head
  ROI_XFORM_METHOD: RoIPoolF
  ROI_XFORM_RESOLUTION: 7
  MLP_HEAD_DIM: 4096
TRAIN:
  SCALES: (480, 576, 688, 864, 1200)
  MAX_SIZE: 2000
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 4096
  PROPOSAL_FILES: ('data/selective_search_data/voc_2012_trainval.pkl',)
TEST:
  SCALE: 480
  MAX_SIZE: 2000
  NMS: 0.3
  PROPOSAL_FILES: ('data/selective_search_data',)
  BBOX_AUG:
    ENABLED: True
    H_FLIP: True
    SCALES: (576, 688, 864, 1200)
    SCALE_H_FLIP: True
    SCORE_HEUR: 'AVG'
    COORD_HEUR: 'AVG'
RNG_SEED: 4
